apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-logger
  labels:
    app: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: log-collector
          image: busybox
          command: ["sh", "-c", "while true; do echo 'Logging...'; sleep 10; done"]
